name: release
on:
  repository_dispatch:
permissions:
  checks: write
  pages: write
  packages: write
  deployments: write
  contents: write
  id-token: read
  issues: read
  pull-requests: read
  security-events: write
  statuses: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
          fetch-depth: 0
      - name: Caches local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: '${{ runner.os }}-maven-'
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '17'
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: Generate git version
        id: generate-version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: development
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: 'dist/*'
          body: '${{ steps.changelog.outputs.changes }}'
          token: '${{ secrets.GITHUB_TOKEN }}'
          commit: develop
          name: 'Version ${{ steps.generate-version.outputs.version }}'
          prerelease: true
          tag: '${{ steps.generate-version.outputs.version }}'


